// Writes src/source.ts: the prototype runtime bundled with MSW, as a string,
// so a host serves it from its own route without a build step of its own.
// Run after editing src/runtime.ts (or upgrading msw); the package test fails
// while the bundle is older than its sources.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
const result = await build({
  entryPoints: [here("../src/runtime.ts")],
  bundle: true,
  write: false,
  format: "iife",
  platform: "browser",
  target: ["es2020"],
  minify: true,
  legalComments: "none",
  define: { "process.env.NODE_ENV": '"production"' },
  plugins: [
    {
      name: "no-cookie-store",
      setup(b) {
        b.onResolve({ filter: /cookieStore\.m?js$/ }, (args) =>
          args.importer.includes(`${"msw"}`) ? { path: here("../src/shims/cookieStore.ts") } : undefined,
        );
      },
    },
  ],
});
const code = result.outputFiles[0].text;
const inputs = ["../src/runtime.ts", "../src/protocol.ts", "../src/openapi.ts", "../src/shims/cookieStore.ts", "./build.mjs"].map((p) => readFileSync(here(p), "utf8")).join("\n");
const msw = JSON.parse(readFileSync(here("../../../node_modules/msw/package.json"), "utf8")).version;
const hash = createHash("sha256").update(inputs + msw).digest("hex").slice(0, 16);
writeFileSync(
  here("../src/source.ts"),
  `// Generated by scripts/build.mjs from src/runtime.ts and msw ${msw}. Do not edit.\n\nexport const PROTOTYPE_SOURCE_HASH = ${JSON.stringify(hash)};\n\nexport const PROTOTYPE_SOURCE: string = ${JSON.stringify(code)};\n`,
);
console.log(`source.ts: ${code.length} characters, sources ${hash}`);
