// Writes src/source.ts: the inspector script as a string, so a host can serve
// it from its own route without reading files at run time. Run after editing
// src/inspector.js; the package test fails while the two disagree.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));
const source = readFileSync(here("../src/inspector.js"), "utf8");
const out = `// Generated by scripts/build.mjs from src/inspector.js. Do not edit.\n\nexport const INSPECTOR_SOURCE: string = ${JSON.stringify(source)};\n`;
writeFileSync(here("../src/source.ts"), out);
console.log(`source.ts: ${source.length} characters`);
