export { buildDtcg, tokenTypeFor, weightOf, type FigmaStyles, type FigmaTextStyle, type FigmaEffect } from "./dtcg";
export { convertFigma, renderReference, figmaIds, boxShadow, bindVariables, inlineUndefinedVars, type FigmaNodeEffect, type ConvertInput, type ConvertReport, type InstanceInfo } from "./convert";
export { compareImages, renderPage, DEFAULT_THRESHOLD, type FidelityResult } from "./fidelity";
export { compareDocuments, isFreeAttribute, type LockChange } from "./lock";
export { googleFontFiles, fontFaceCss, fontFileName, type FontFile } from "./fonts";
export { checksum, script, INVENTORY, VARIABLES, STYLES, NODE_MAP, COMPONENT, EXPORT_SVG, EFFECTS, GATE, BINDINGS } from "./scripts";
export { alignText, markTextElements, type TextNudge } from "./align";
export { applyUpgrade, revertUpgrade, type UpgradeOp, type UpgradeResult } from "./semantic";
export { outline, outlineText, type OutlineRow } from "./semantic";
export { inspectNodes, evaluateGate, gateMarkdown, gateCovers, GATE_RULES, type GateFacts, type GateHit, type GateReport, type GateResult, type GateSeverity } from "./gate";
export { carryIds } from "./carry";
export { errorParts, errorElement, linkStates, withErrorParts, type ErrorPart } from "./states";
